name: Build EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install
      run: |
        pip install pyinstaller PyQt5
    - name: Build
      run: |
        pyinstaller --onefile --windowed --name "BenchManager" main.py
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: BenchManager
        path: dist/BenchManager.exe
